//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Bank_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposite_Tb
    {
        public int Id { get; set; }
        public Nullable<decimal> Accnumber { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public Nullable<decimal> DepAmount { get; set; }
        public string Date { get; set; }
    }
}
