//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Bank_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankingEntities1 : DbContext
    {
        public BankingEntities1()
            : base("name=BankingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deposite_Tb> Deposite_Tb { get; set; }
        public virtual DbSet<Login_Tb> Login_Tb { get; set; }
        public virtual DbSet<Register_Tb> Register_Tb { get; set; }
        public virtual DbSet<Transefer_Tb> Transefer_Tb { get; set; }
        public virtual DbSet<User_Account> User_Account { get; set; }
        public virtual DbSet<Acc_Tb> Acc_Tb { get; set; }
        public virtual DbSet<Customer_Tb> Customer_Tb { get; set; }
    }
}
