//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Bank_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account
    {
        public int Account_Num { get; set; }
        public string Name { get; set; }
        public string DDB { get; set; }
        public string Phone_Num { get; set; }
        public string state { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string Social_status { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Date { get; set; }
    }
}
